name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2 
      with:
        version: '6.0.1'
        tools: 'tools_ifw,4.0,qt.tools.ifw.40 tools_qtcreator,4.13.2-0,qt.tools.qtcreator'
    - name: log
      run: dir "../Qt/Tools/QtCreator/bin/"
      shell: cmd
    - name: make
      run: "../Qt/Tools/QtCreator/bin/jom.exe TRSE.pro"
      
